from typing import Protocol
from uuid import UUID

from app.domain.entities.token import PasswordResetToken, RefreshToken


class RefreshTokenRepository(Protocol):
    async def save(self, token: RefreshToken) -> RefreshToken: ...
    async def find_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token_id: UUID) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...
    async def count_active_for_user(self, user_id: UUID) -> int: ...


class PasswordResetTokenRepository(Protocol):
    async def save(self, token: PasswordResetToken) -> PasswordResetToken: ...
    async def find_by_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def mark_as_used(self, token_id: UUID) -> None: ...
