"""add_soft_delete_to_books

Revision ID: d4416611cdb1
Revises: 6b84659de5d7
Create Date: 2026-06-25 00:27:07.757548+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4416611cdb1"
down_revision: str | None = "6b84659de5d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "books", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "deleted_at")
    op.drop_column("books", "is_deleted")
    # ### end Alembic commands ###
