"""Add ReadingNote model

Revision ID: 9808c38d53c6
Revises: 57f9eac257da
Create Date: 2026-06-25 16:21:22.936293+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9808c38d53c6'
down_revision: Union[str, None] = '57f9eac257da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_notes_book_id'), 'reading_notes', ['book_id'], unique=True)
    op.create_index(op.f('ix_reading_notes_user_id'), 'reading_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_notes_user_id'), table_name='reading_notes')
    op.drop_index(op.f('ix_reading_notes_book_id'), table_name='reading_notes')
    op.drop_table('reading_notes')
    # ### end Alembic commands ###
