"""add_optional_book_fields

Revision ID: 6b84659de5d7
Revises: f1318b725bba
Create Date: 2026-06-24 18:40:07.665515+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b84659de5d7'
down_revision: Union[str, None] = 'f1318b725bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('total_pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'total_pages')
    op.drop_column('books', 'published_year')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###
