"""add_isbn_to_books

Revision ID: 82f68a460641
Revises: d4416611cdb1
Create Date: 2026-06-25 00:42:08.448547+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f68a460641'
down_revision: Union[str, None] = 'd4416611cdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=50), nullable=True))
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('books', 'cover_url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'cover_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('books', 'publisher',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
