"""add genres and rating to books

Revision ID: 2390d258881d
Revises: 9808c38d53c6
Create Date: 2026-06-25 17:33:47.522265+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2390d258881d"
down_revision: str | None = "9808c38d53c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "genres", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
    )
    op.add_column("books", sa.Column("rating", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "rating")
    op.drop_column("books", "genres")
    # ### end Alembic commands ###
